services:
  - type: web
    name: teyzoo-signal-bot
    runtime: python
    plan: free

    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT

    healthCheckPath: /health

    autoDeploy: true

    envVars:
      - key: PYTHON_VERSION
        value: "3.13.11"

      - key: BOT_TOKEN
        sync: false

      - key: DATABASE_URL
        sync: false

      - key: TWELVE_DATA_API_KEY
        sync: false

      - key: ADMIN_IDS
        sync: false

      - key: OWNER_IDS
        sync: false

      - key: HOST
        value: 0.0.0.0

      - key: PORT
        value: "10000"

      - key: HEALTH_PATH
        value: /health

      - key: TIMEZONE
        value: Europe/Moscow

      - key: AUTO_SIGNAL_INTERVAL_MINUTES
        value: "20"
